### ISSUE TITLE
[FR] Service key credentials should have db owner role for Azure SQL

### ISSUE THREAD

**Issue by claassen** [cloudfoundry-incubator/csb-brokerpak-azure#13]
Users are unable to generate query plans using service key credentials, the old MASB broker gave service key credentials db_owner role access, so looking to match that.

**Comment by erniebilling** [comment]
Available in https://github.com/cloudfoundry-incubator/csb-brokerpak-azure/releases/tag/1.0.0-rc.38

Will be released in tile once https://github.com/cloudfoundry-incubator/csb-brokerpak-azure/issues/10 is resolved.
