### ISSUE TITLE
[DOCS] Handling multiple azure_subscription_id, azure_client_id and azure_client_secret with Azure Brokerpack

### ISSUE THREAD

**Issue by drebake** [cloudfoundry-incubator/csb-brokerpak-azure#2]
## Documentation Requested 
I would like to know if it's possible to use multiple azure_subscription_id, azure_client_id and azure_client_secret with the Azure Brokerpack.

Currently, we have our main azure_subscription_id, azure_client_id and azure_client_secret configured in the tile.

We would like to send some services to a different azure_subsciption, so I would like to know if it's possible to set different default settings on a plan basis or create different Azure services that would create the service on a different subscription then the default configured one in the tile?

We are changing our deployment model and creating different servers for each orgs, so we need to be able to handle multiple subscriptions or else we hit Azure limits on the amount of resource-groups and/or Azure servers within a subscription.

If we can have a discussion or documentation/recommendation on how to handle this case it would be appreciated.

**Comment by drebake** [comment]
I was able to test successfully but have a follow up question.

When we set a default setting in a plan, is that value taken as a default setting or overrides the user provided setting at the cf CLI?

Reason I asked is because when I specify a server in the plan, I can't seem to override that value with using the parameters in the cf CLI. Is that only for the server parameter or all parameters?

If it overrides it, it means I would be able to lock user provided parameters by setting those options in the plan? (Which is something we're looking to do for some parameters).

**Comment by drebake** [comment]
@erniebilling Would it be possible to answer my previous quesiton? I'll then be able to close this issue.

Thanks!

**Comment by erniebilling** [comment]
@drebake sorry for my tardiness on this. Any plan provided value will override any use provided value. So if a value is set in the plan, a user may not override with `-c {...}`

Does that help?

**Comment by drebake** [comment]
Yes, exactly the confirmation I was looking for. 
Thanks
