### ISSUE TITLE
[BUG] App binding credentials do not work after performing failover of Azure SQL DB

### ISSUE THREAD

**Issue by claassen** [cloudfoundry-incubator/csb-brokerpak-azure#4]
It seems that when creating a csb-azure-mssql-db-failover-group instance and binding to an app, the login is created in the master database, and so does not get replicated to the secondary database. After performing a failover the credentials for the app binding no long work, and it is also not possible to unbind/rebind to create new credentials as it fails to unbind due to not being able to find the login that it created before.

Steps to reproduce:

1. Create FOG DB instance:

```
cf create-service csb-azure-mssql-db-failover-group StandardS0 csb-failover-group-test -c '{"instance_name": "csb-failover-group-test", "db_name": "csb-db-test"}'
```

2. Push app and bind to created service
3. Perform failover:

```
cf create-service csb-azure-mssql-fog-run-failover standard my-failover -c '{"fog_instance_name":"csb-failover-group-test"}'
```

4. Restart app, app binding credentials are no longer valid. Trying to unbind the service from the app also fails

Creating a new binding via a service key after performing failover works, as a new login is created in the secondary master DB, but this does not work for apps with existing bindings.

**Comment by claassen** [comment]
It seems a possible solution is to use 'contained' users: https://docs.microsoft.com/en-us/sql/relational-databases/security/contained-database-users-making-your-database-portable?view=sql-server-ver15

**Comment by erniebilling** [comment]
Is this a new issue? Or do you believe the broker has always performed this way?

**Comment by claassen** [comment]
I am not 100% sure, but I am pretty sure I had tested this at some point in the past and it worked, but it could have just been because I actually created a new binding after performing the failover.
